name: Linux

on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/linux.yml'
    - 'backend/**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: cargo install cross

    - name: build
      run: cd backend && cross update && cross build --target=i686-pc-windows-gnu --release

    - name: Package Files
      id: package
      shell: bash
      run: >
        cp ./backend/target/i686-pc-windows-gnu/release/renegade-x-launcher.exe "./Renegade X Launcher.exe";
        zip -j9 RenX-Launcher "Renegade X Launcher.exe" "RenegadeX-folder-permissions.exe" "sciter.dll" "SelfUpdateExecutor.exe";
        zip -9 RenX-Launcher -r "dom";

    - uses: actions/upload-artifact@v3
      with:
        name: RenX-Launcher
        path: RenX-Launcher.zip